package com.cmind.entity;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class Employee {/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Id
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.id
	 * @return  the value of employee.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.id
	 * @param id  the value for employee.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.name
	 * @return  the value of employee.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.name
	 * @param name  the value for employee.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.password
	 * @return  the value of employee.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.password
	 * @param password  the value for employee.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
}