package com.cmind.entity;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class Staff {/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Id
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.id
	 * @return  the value of staff.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.id
	 * @param id  the value for staff.id
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.name
	 * @return  the value of staff.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.name
	 * @param name  the value for staff.name
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.password
	 * @return  the value of staff.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.password
	 * @param password  the value for staff.password
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
}