package com.cmind.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cmind.entity.Employee;
import com.cmind.entity.EmployeeExample;

@Mapper
public interface EmployeeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Delete({ "delete from employee", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Insert({ "insert into employee (id, name, ", "password)",
			"values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ", "#{password,jdbcType=VARCHAR})" })
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Select({ "select", "id, name, password", "from employee", "where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("com.cmind.mybatis.mapper.EmployeeMapper.BaseResultMap")
	Employee selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Update({ "update employee", "set name = #{name,jdbcType=VARCHAR},", "password = #{password,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Employee record);

	@Select({
        "select * from employee where name = #{name} limit 1"
    })
    Employee selectByName(String name);
}