package com.cmind.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cmind.entity.Staff;
import com.cmind.entity.StaffExample;

@Mapper
public interface StaffMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	long countByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int deleteByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Delete({ "delete from staff", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Insert({ "insert into staff (id, name, ", "password)",
			"values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ", "#{password,jdbcType=VARCHAR})" })
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int insertSelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	List<Staff> selectByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Select({ "select", "id, name, password", "from staff", "where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("com.cmind.mybatis.mapper.StaffMapper.BaseResultMap")
	Staff selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Staff record, @Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExample(@Param("record") Staff record, @Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByPrimaryKeySelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Update({ "update staff", "set name = #{name,jdbcType=VARCHAR},", "password = #{password,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Staff record);

	@Select({
        "select * from staff where id = #{id} limit 1"
    })
    Staff selectById(String id);
}